"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {api,Decision,Task} from "@/lib/api";

export default function Tasks(){
 const [tasks,setTasks]=useState<Task[]>([]),[decision,setDecision]=useState<Decision|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=()=>api.tasks().then(setTasks).catch(e=>setError(String(e))); useEffect(()=>{load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const t=await api.createTask({title:f.get("title"),description:f.get("description"),task_type:f.get("task_type"),risk_level:f.get("risk"),sensitive_area:f.get("area")||null,constraints:{require_tests:true,require_behavior_preservation:f.get("preserve")==="on",require_human_approval:f.get("approval")==="on",max_execution_seconds:300,budget_units:100}});setDecision(await api.route(t.id));await load()}catch(err){setError(String(err))}finally{setBusy(false)}}
 return <><section className="hero"><div className="eyebrow">Engineering tasks</div><h1>Create, route, and learn from verified outcomes.</h1><p>The default form represents the first golden-path task: a genuinely low-risk targeted billing-formatting change. With no comparable failure evidence, production policy should choose FAST.</p></section>
 <div className="two section"><div className="card"><form onSubmit={submit}><label>Title<input name="title" defaultValue="Normalize billing currency output" required/></label><label>Description<textarea name="description" defaultValue="Make the billing output formatting consistent with a targeted change." required/></label><div className="row"><label>Task type<select name="task_type" defaultValue="formatting_fix"><option value="formatting_fix">Formatting fix</option><option value="bug_fix">Bug fix</option><option value="investigation">Investigation</option><option value="refactor">Refactor</option><option value="documentation">Documentation</option></select></label><label>Risk<select name="risk" defaultValue="low"><option>low</option><option>medium</option><option>high</option></select></label></div><label>Sensitive area<select name="area" defaultValue="billing_formatting"><option value="billing_formatting">Billing formatting</option><option value="">None</option><option value="financial_logic">Financial logic</option><option value="auth">Authentication</option><option value="security">Security</option><option value="parser">Parser</option></select></label><div className="checks"><label><input type="checkbox" name="preserve"/> Mandatory behavior preservation</label><label><input type="checkbox" name="approval"/> Mandatory human approval</label></div><button disabled={busy}>{busy?"Routing…":"Create + production route"}</button>{error&&<div className="notice">{error}</div>}</form></div>
 <div className="card decision"><div className="label">Latest route decision</div>{decision?<><div className={`metric ${decision.workflow}`}>{decision.workflow}</div><p>{decision.rationale}</p><div className="label">Why Tessera chose it</div><div className="chips">{decision.reason_codes.map(x=><span className="pill" key={x}>{x}</span>)}</div><div className="scoregrid">{Object.entries(decision.candidate_scores).map(([k,v])=><div key={k}><b className={k}>{k}</b><span>{v===null?"Ineligible":v}</span></div>)}</div></>:<p className="muted">Create a task to see the production decision and its evidence.</p>}</div></div>
 <section className="section"><div className="sectionHead"><h2>Task history</h2><span className="muted">{tasks.length} records</span></div><table className="table"><thead><tr><th>Task</th><th>Risk</th><th>Sensitive area</th><th>ID</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td>{t.title}</td><td>{t.risk_level}</td><td>{t.sensitive_area??"—"}</td><td><Link href={`/tasks/${t.id}`} className="muted">{t.id}</Link></td></tr>)}</tbody></table></section></>
}
